// <auto-generated />
namespace CopyCatsDetective.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class loss : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(loss));
        
        string IMigrationMetadata.Id
        {
            get { return "201401310040380_loss"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
